### ISSUE TITLE
Collision Nodes

### ISSUE THREAD

**Issue by JimmyD1812** [daemitus/ClickLib#4]
Hey new /click user from SND
Trying to explore what can be done and I am seeing things are limited to predefined buttons or list of strings, was wondering if you could incorporate "Collision Node" ID to find a target to click (/click collision_node 2C####### for example). 

I have no idea what I'm doing and if this is unfeasible or your already working on it, feel free to just ignore this - https://imgur.com/a/SoMU1OT

**Comment by daemitus** [comment]
So they're not actually clicks. I'm calling the event handlers that the
click would be routed to. Actual clicks were always wonky in various ways

**Comment by JimmyD1812** [comment]
> So they're not actually clicks. I'm calling the event handlers that the click would be routed to. Actual clicks were always wonky in various ways

I see, is there a function I'm overlooking to send event handler IDs directly to the plugin? If so can these IDs be found in /xldata?

**Comment by daemitus** [comment]
Not really, each window registers buttons as an arbitrary number that you
basically need to reverse or hook to figure out. I've never tried to
genericize it yet

**Comment by JimmyD1812** [comment]
Ah okay, well thank you for your hard work! You've made crafting a lot more managable :)
